### ISSUE TITLE
SSPI Explodes with out of memory when passed a negotiate token instead of a native kerberos token

### ISSUE THREAD

**Issue by Geobert** [estokes/cross-krb5#2]
Hi, 

thank you so much for this crate which make things way simpler!

I'm trying to use this crate to accept a token received from Active Directory and I get this failure:
```
ServerCtx::step failed Not enough memory is available to complete this request
```

I tried a quick and dirty `accept(None, token)` to get this error

and the platform is Windows 2019 server in an Hyper-V VM with dynamic RAM management (up to 10GB).  

Any clue on how to allocate more memory for the underneath of `accept` call?

**Comment by estokes** [comment]
Sorry you're having an issue. I'm by no means an expert in windows much less SSPI, I read some api docs and wrote code :). That said this is a pretty strange error, considering it shouldn't take a lot or memory to accept a kerberos token, we're talking kbytes if that. I have never tried this code inside a hyper-v VM before, is it possible to try on bare metal, just to eliminate the VM from the equation? As far as "allocating more memory" to my knowledge the SSPI api does not include any memory management primitives or knobs. If you continue to have an issue I'd recommend you run the program with a memory profiler to find out where (and hopefully why) malloc is failing.

**Comment by estokes** [comment]
a quick google search later reveals that our friends in the Python community hit this in 2011

https://mail.python.org/pipermail/python-win32/2011-April/011427.html

**Comment by Geobert** [comment]
> @Geobert an additional question for you. Is it correct that you did not generate the token with cross-krb5?

Correct. I have a setup with a Windows Server with Active Directory, a Windows client that uses this AD for users management, on their own network. From the client, I trigger a browser that hit my app on server and I challenge the browser (which has been configured to do ntlm auth on the domain) and it sent me a token after getting it from AD.

It's supposed to use Kerberos but it's true that I'm unsure of it.

I'm not a specialist either, I'm learning on the go  ^^

Here is the RFC: https://datatracker.ietf.org/doc/html/rfc4559

**Comment by estokes** [comment]
There is a way, by altering the SSPI code, I need to think about how to do it without breaking everything else in the process. Microsoft decided not to support the standard gssapi interface when they introduced active directory in 2000, that's why we're having this fun conversation. If your application is windows only and will never need to interoperate with any other OS you can just use sspi directly, the api isn't as nice, but you can process any kind of token you want.

**Comment by estokes** [comment]
I did a quick read of the code and I think to try the "python fix" all you'd have to do is change 'Kerberos' to 'Negotiate' in the credentials section, that seems to define the "package" which sets the token type.

**Comment by estokes** [comment]
something like that sounds promising, I'll give it some thought today.

**Comment by estokes** [comment]
Try your app with the latest git, if it works for you I'll cut a release

**Comment by Geobert** [comment]
> Try your app with the latest git, if it works for you I'll cut a release.
> 
> For posterity, I figured probably over time tons of these "little tweaks" will come up, so I just went ahead and added a bitflags arg to accept and initiate.

Just did a test and it works, thank you very much for looking into this!

**Comment by estokes** [comment]
No problem, I need to run some additional tests and then I'll cut a release.
